cache:
  paths:
  - node_modules/

stages:
- test
- build
- deploy

test_application:
  image: node:4.2.2
  stage: test
  tags:
   - docker
  script:
   - npm install
   - npm test

build_app:
  stage: build
  tags:
   - sh
  script:
    - echo "Building application..."
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN gitlab-stage.cee.redhat.com:4567
    - docker build -t gitlab-stage.cee.redhat.com:4567/savsingh/nodejs .
    - docker push gitlab-stage.cee.redhat.com:4567/savsingh/nodejs

staging:
  stage: deploy
  tags:
   - sh
  script:
   - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN gitlab-stage.cee.redhat.com:4567
   - docker pull gitlab-stage.cee.redhat.com:4567/savsingh/nodejs
   - docker stop nodejs-stage || true && docker rm nodejs-stage || true
   - docker run --name=nodejs-stage -p 8081:8080 -itd gitlab-stage.cee.redhat.com:4567/savsingh/nodejs:latest
  except:
   - master
  environment: 
    name: staging
    url: http://10.65.8.23:8081

production:
  stage: deploy
  tags:
   - sh
  script:
   - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN gitlab-stage.cee.redhat.com:4567
   - docker pull gitlab-stage.cee.redhat.com:4567/savsingh/nodejs
   - docker stop nodejs || true && docker rm nodejs || true
   - docker run --name=nodejs -p 8080:8080 -itd gitlab-stage.cee.redhat.com:4567/savsingh/nodejs:latest
  only:
   - master
  environment:
    name: production
    url: http://10.65.8.23:8080
